language: ruby
before_install:
  - echo "before_install"
script:
  - uname -a
  - ls -al /etc/
  - cat /etc/debian_version
  - rubocop .
  - foodcritic .
notifications:
  email:
    recipients:
      - psantosh@us.ibm.com
    on_success: change
    on_failure: always
