language: ruby
before_install:
  - echo "before_install"
script:
  - echo "script"
  - pwd
  - ls -al
notifications:
  email:
    recipients:
      - psantosh@us.ibm.com
    on_success: change
    on_failure: always
