language: ruby
before_install:
  # Install ChefDK
  - wget https://packages.chef.io/files/stable/chefdk/1.3.43/debian/7/chefdk_1.3.43-1_amd64.deb -O /tmp/chefdk.deb
  - sudo dpkg -i /tmp/chefdk.deb
  # Set ChefDK ruby as system ruby
  - eval "$(chef shell-init bash)"
script:
  # Vet the code
  - rubocop recipes
  - foodcritic .
  - chef exec rspec
notifications:
  email:
    recipients:
      - psantosh@us.ibm.com
    on_success: change
    on_failure: always
